version: "3.9"
services:
  api_gateway:
    container_name: api_gateway
    image: devopsfaith/krakend
    ports:
      - "8080:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    networks:
      - common_network

  users_db:
    container_name: users_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5438:5432"
    networks:
      - common_network

  users:
    container_name: users
    build:
      context: ./users
      dockerfile: Dockerfile
    volumes:
      - ./users:/app
    depends_on:
      - users_db
      - rabbitmq
    networks:
      - common_network

  notifications_db:
    container_name: notifications_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - common_network

  notifications:
    container_name: notifications
    build:
      context: ./notifications
      dockerfile: Dockerfile
    volumes:
      - ./notifications:/app
    depends_on:
      - rabbitmq
      - notifications_db
    networks:
      - common_network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - common_network

networks:
  common_network:
